# Generated by Django 5.2.8 on 2025-11-30 23:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembresiaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(default=django.utils.timezone.now)),
                ('activa', models.BooleanField(default=True)),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.membresia')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='MembresiaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_incluida', models.PositiveIntegerField(help_text='Número de veces que se puede usar este servicio con esta membresía.')),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_incluidos', to='servicios.membresia')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='UsoMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_uso', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad_usada', models.PositiveIntegerField(default=1)),
                ('membresia_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='servicios.membresiapaciente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.servicio')),
            ],
        ),
    ]
