# Generated by Django 5.2.8 on 2025-11-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('sucursal', models.CharField(max_length=100)),
                ('nutriologa', models.CharField(max_length=100)),
                ('servicio', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('notas', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
